# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
#add blank line between prompts
add_newline = true
follow_symlinks = false

[directory]
#truncate using "..." if path is long
truncation_length = 3
truncation_symbol = ">>"
truncate_to_repo = true
read_only = "ğŸ”’"
read_only_style = "red"
format = "[$path]($style) "
style = "bold purple"

[character]
success_symbol = "[âœ](bold green) "
error_symbol   = "[âœ˜](bold red) "
vicmd_symbol   = "[â®](bold purple) "

[cmd_duration] 
min_time = 500
format = 'ttc [$duration](bold purple)'

